/anaconda2/lib/python2.7/site-packages/dfols/solver.py:878: RuntimeWarning: maxfun <= npt: Are you sure your budget is large enough?
  warnings.warn("maxfun <= npt: Are you sure your budget is large enough?", RuntimeWarning)
hi
Running from config ../Configurations/OxfordMOPS_Configs/TWIN_Configs/OxfordMOPS_dfols_twin_6p.json named dfols_twin_6param
('init params_to_pass', [])
*** Model in test6pars/dfo001 has no observations so ignoring ****
No covtotal found for totalFile= None
Scaling CovTotal
running DFOLS *********
(u'ro2ut', '170', u'ACik', '24', u'ACkpo4', '0.03125', u'ACmuzoo', '2', u'AComniz', '3.2', u'detmartin', '0.858', 'refDir', u'/Users/orie3677/Documents/Uni/Project/Optimization/OptClim/Configurations/OxfordMOPS_Configs/RunCode')
None
Need to make  (u'ro2ut', '170', u'ACik', '24', u'ACkpo4', '0.03125', u'ACmuzoo', '2', u'AComniz', '3.2', u'detmartin', '0.858', 'refDir', u'/Users/orie3677/Documents/Uni/Project/Optimization/OptClim/Configurations/OxfordMOPS_Configs/RunCode')
we got to 532
('Param = ', ro2ut        170.00000
ACik          24.00000
ACkpo4         0.03125
ACmuzoo        2.00000
AComniz        3.20000
detmartin      0.85800
dtype: float64)
('pDict = ', OrderedDict([(u'ro2ut', 170.0), (u'ACik', 24.0), (u'ACkpo4', 0.03125), (u'ACmuzoo', 2.0), (u'AComniz', 3.2), (u'detmartin', 0.858)]))
('init params_to_pass', OrderedDict([(u'ro2ut', 170.0), (u'ACik', 24.0), (u'ACkpo4', 0.03125), (u'ACmuzoo', 2.0), (u'AComniz', 3.2), (u'detmartin', 0.858), ('RUNID', 'dfo001')]))
('init params_to_pass', OrderedDict([(u'ro2ut', 170.0), (u'ACik', 24.0), (u'ACkpo4', 0.03125), (u'ACmuzoo', 2.0), (u'AComniz', 3.2), (u'detmartin', 0.858), ('RUNID', 'dfo001')]))
MOPS setParams def running ***********
('/Users/orie3677/Documents/Uni/Project/Optimization/OptClim/OxfordMOPS/test6pars/dfo001/parameters_input.txt', OrderedDict([(u'ro2ut', 170.0), (u'ACik', 24.0), (u'ACkpo4', 0.03125), (u'ACmuzoo', 2.0), (u'AComniz', 3.2), (u'detmartin', 0.858), ('RUNID', 'dfo001')]))
('/Users/orie3677/Documents/Uni/Project/Optimization/OptClim/OxfordMOPS/test6pars/dfo001/parameters_names.txt', OrderedDict([(u'ro2ut', 170.0), (u'ACik', 24.0), (u'ACkpo4', 0.03125), (u'ACmuzoo', 2.0), (u'AComniz', 3.2), (u'detmartin', 0.858), ('RUNID', 'dfo001')]))
createDir is test6pars/dfo001 path is /Users/orie3677/Documents/Uni/Project/Optimization/OptClim/OxfordMOPS
test6pars/OxfordMOPS_dfols_twin_6p_final.json
Submitting  /Users/orie3677/Documents/Uni/Project/Optimization/OptClim/OxfordMOPS/test6pars/dfo001/runscript
Traceback (most recent call last):
  File "/Users/orie3677/Documents/Uni/Project/Optimization/OptClim/OxfordMOPS/runOptimise.py", line 606, in <module>
    resubmit=restartCMD, runCode=runCode) # submit the models
  File "/Users/orie3677/Documents/Uni/Project/Optimization/OptClim/OxfordMOPS/Submit.py", line 187, in arcSubmit
    subprocess.check_output(modelSubmitName, shell=True) # submit the script
  File "/anaconda2/lib/python2.7/subprocess.py", line 213, in check_output
    output, unused_err = process.communicate()
  File "/anaconda2/lib/python2.7/subprocess.py", line 471, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/anaconda2/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
